services:
  - type: web
    name: cheesy-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_CRED_JSON
        value: ./cheesydelight-80a43-firebase-adminsdk-fbsvc-2e5458d166.json
      - key: FIREBASE_DB_URL
        value: https://cheesydelight-80a43-default-rtdb.firebaseio.com
      - key: ADMIN_API_KEY
        value: super-secret-admin-key
      - key: PYO3_USE_ABI3_FORWARD_COMPATIBILITY
        value: "1"  # 🧠 prevents Rust build
